jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: server

      - name: Check target directory
        run: ls -la server/target 

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t miguel184/reelradarapi -f server/docker/Dockerfile ./server

      - name: Push Docker image
        run: docker push miguel184/reelradarapi
